# Deployments
deployments: []
  # - name: example-deployment
  #   replicaCount: 1
  #   image:
  #     repository: your-registry/example-app
  #     tag: latest
  #     pullPolicy: IfNotPresent
  #   containerPort: 80

# Services
services: []
  # - name: example-service
  #   type: ClusterIP
  #   port: 80
  #   selector: example-deployment

# Ingresses
ingresses: []
  # - name: example-ingress
  #   annotations:
  #     kubernetes.io/ingress.class: nginx
  #   host: chart-example.local
  #   serviceName: example-service
  #   servicePort: 80
  #   path: /
  #   pathType: Prefix
  #   tls: false
  #   tlsSecretName: chart-example-tls

# ConfigMaps
configMaps: []
  # - name: example-config
  #   data:
  #     APP_CONFIG: |
  #       key1: value1
  #       key2: value2

# Databases
databases: []
  # - name: example-db
  #   dbName: example-db
  #   psqlClusterName: home-postgres-cluster
  #   allowConnections: true

# StatefulSets
statefulSets: []
  # - name: example-statefulset
  #   serviceName: example-statefulset-svc
  #   replicaCount: 1
  #   image:
  #     repository: your-registry/example-stateful-app
  #     tag: latest

# DaemonSets
daemonSets: []
  # - name: example-daemonset
  #   image:
  #     repository: your-registry/example-daemon-app
  #     tag: latest

# Jobs
jobs: []
  # - name: example-job
  #   image:
  #     repository: your-registry/example-job-app
  #     tag: latest
  #   restartPolicy: OnFailure

# CronJobs
cronJobs: []
  # - name: example-cronjob
  #   schedule: "0 * * * *"
  #   image:
  #     repository: your-registry/example-cron-app
  #     tag: latest
  #   restartPolicy: OnFailure

# ExternalS3Secrets
externalS3Secrets: []

# ExternalRegistrySecrets
externalRegistrySecrets: []

{% if cookiecutter.need_dep_chart == 'yes' %}
{{ cookiecutter.dep_chart_name }}:
  # Values for the dependency chart will be populated here
{% endif %}
