{{- if .Values.databases }}
{{- range .Values.databases }}
---
apiVersion: theramirez.casa/v1alpha1
kind: DB
metadata:
  name: {{ .name }}
spec:
  dbName: {{ .dbName }}
  psqlClusterName: {{ .psqlClusterName }}
{{- end }}
{{- end }}
