{{- if .Values.deployments }}
{{- range .Values.deployments }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .name }}
spec:
  replicas: {{ .replicaCount | default 1 }}
  selector:
    matchLabels:
      app: {{ .name }}
  template:
    metadata:
      labels:
        app: {{ .name }}
    spec:
      containers:
      - env:
        - secretRef:
            name: "{{ .s3Secret }}"
            optional: false
        - name: {{ .name }}
          image: "{{ .image.repository }}:{{ .image.tag }}"
          imagePullPolicy: {{ .image.pullPolicy | default "IfNotPresent" }}
          ports:
            - name: http
              containerPort: {{ .containerPort | default 80 }}
              protocol: TCP
      imagePullSecrets:
      - name: "{{ .image.pullSecret }}"
{{- end }}
{{- end }}
