{{- if .Values.ingresses }}
{{- range .Values.ingresses }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .name }}
  annotations:
    {{- toYaml .annotations | nindent 4 }}
spec:
  rules:
    - host: {{ .host }}
      http:
        paths:
          - path: {{ .path | default "/" }}
            pathType: {{ .pathType | default "Prefix" }}
            backend:
              service:
                name: {{ .serviceName }}
                port: 
                  number: {{ .servicePort }}
  {{- if .tls }}
  tls:
    - hosts:
        - {{ .host }}
      secretName: {{ .tlsSecretName }}
  {{- end }}
{{- end }}
{{- end }}
