{{- if .Values.services }}
{{- range .Values.services }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .name }}
spec:
  type: {{ .type | default "ClusterIP" }}
  ports:
    - port: {{ .port | default 80 }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ .appSelector }}
{{- end }}
{{- end }}
